### ISSUE TITLE
Don't know how to open the website ( Windows )

### ISSUE THREAD

**Issue by PleaseHelpMeeeeeee** [Shipu/dinero#4]
Like, i don't what's the mail and password, i can't login on the website

Query : select * from `accounts` where `id` is null and `accounts`.`deleted_at` is null limit 1

**Comment by Shipu** [comment]
- Run `php artisan migrate --seed`
- Login with the following credentials:
```
Email: demo@dinero.app
Password: 12345678
```
Read Documentation for more details.

**Comment by PleaseHelpMeeeeeee** [comment]
Still not working, when i want to login in the website just refresh the page and the url's going from localhost/public/login to localhost/public/login?, i got an error in console :

 login:449        GET http://localhost/livewire/livewire.js?id=99a05389 net::ERR_ABORTED 404 (Not Found)
