### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by Sisifo-Developer** [Shipu/dinero#5]
I get the following error when I executed "composer install" :

`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Type of App\Filament\Widgets\CategoryChart::$chartId must be ?string (as in class Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget) in /Users/sisifo/Sites/dinero/app/Filament/Widgets/CategoryChart.php on line 10

   Symfony\Component\ErrorHandler\Error\FatalError

  Type of App\Filament\Widgets\CategoryChart::$chartId must be ?string (as in class Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget)

  at app/Filament/Widgets/CategoryChart.php:10
      6▕ use App\Models\Category;
      7▕ use App\Models\Transaction;
      8▕ use Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget;
      9▕
  ➜  10▕ class CategoryChart extends ApexChartWidget
     11▕ {
     12▕     /**
     13▕      * Chart Id
     14▕      *

   Whoops\Exception\ErrorException

  Type of App\Filament\Widgets\CategoryChart::$chartId must be ?string (as in class Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget)

  at app/Filament/Widgets/CategoryChart.php:10
      6▕ use App\Models\Category;
      7▕ use App\Models\Transaction;
      8▕ use Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget;
      9▕
  ➜  10▕ class CategoryChart extends ApexChartWidget
     11▕ {
     12▕     /**
     13▕      * Chart Id
     14▕      *

      +1 vendor frames

  2   [internal]:0
      Whoops\Run::handleShutdown()

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255`

**Comment by Shipu** [comment]
Try to reproduce but everything works fine.

**Comment by Sisifo-Developer** [comment]
The problem was in php version, I had 8.3.

I swapped to 8.1 and I have installed without problem.

Thanks.
